name: Update Profile Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # refresh every 12 hours
  workflow_dispatch:
  push:
    paths:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test Token Access
        run: |
          curl -H "Authorization: token $GH_TOKEN" https://api.github.com/user > /dev/null

      - name: Done
        run: echo "✅ Private GitHub contributions counted"
